In [ ]:
import pandas as pd
import numpy as np

Name - Shashank Singh

Roll Number - 19289

This code was used for loading and reading the data set using numpy in the form of a matrix, normalising it between [0,1], and for finding the value used for normalising the fitness function. 

The logic behind choosing such a value to normalise the fitness function is to consider the case where each demand point is served by the closest potential hub. And that demand point is served uniquely by that potential hub.

Kindly upload '12_16.csv', '4_8.csv', '8_12.csv' and 'Pot.csv' before running the colab notebook.

In [ ]:
array12_16 = np.loadtxt(open("12_16.csv", "r"), delimiter=",", skiprows=1)  #loading the data frame 12-6.

In [ ]:
array12_16[:4, :4]

array([[1.009e+03, 1.000e+00, 5.200e+01, 7.500e+01],
       [9.270e+02, 2.600e+01, 1.000e+00, 2.000e+01],
       [9.920e+02, 1.790e+02, 1.230e+02, 1.730e+02],
       [9.870e+02, 6.500e+01, 2.900e+01, 1.000e+00]])

In [ ]:
array12_16_norm = (array12_16 - array12_16.min())/(array12_16.max() - array12_16.min()) #code used for normalisation of the array row wise 12-6.

In [ ]:
array12_16_norm[:4,:4] #peeking into the normalised array.

array([[0.36896047, 0.        , 0.01866764, 0.02708638],
       [0.33894583, 0.00915081, 0.        , 0.00695461],
       [0.36273792, 0.06515373, 0.04465593, 0.06295754],
       [0.36090776, 0.02342606, 0.0102489 , 0.        ]])

In [ ]:
array8_12 = np.loadtxt(open("8_12.csv", "r"), delimiter=",", skiprows=1) #loading the data frame 8-12.

In [ ]:
array8_12_norm = (array8_12 - array8_12.min())/(array8_12.max() - array8_12.min()) #code used for normalisation of the array row wise time 8-12.

In [ ]:
array8_12_norm[:4,:4] #peeking into the normalised array.

array([[0.37354651, 0.        , 0.02579942, 0.03415698],
       [0.34375   , 0.01635174, 0.        , 0.01417151],
       [0.36736919, 0.07194767, 0.05159884, 0.06976744],
       [0.36555233, 0.03052326, 0.01744186, 0.        ]])

In [ ]:
array4_8 = np.loadtxt(open("4_8.csv", "r"), delimiter=",", skiprows=1) #loading the data frame 4-8.

In [ ]:
array4_8_norm = (array4_8 - array4_8.min())/(array4_8.max() - array4_8.min()) #code used for normalisation of the array row wise time 4-8.

In [ ]:
array4_8_norm[:4,:4] #peeking into the normalised array.

array([[0.32179386, 0.        , 0.03186467, 0.04091267],
       [0.2895358 , 0.02163651, 0.        , 0.01927616],
       [0.31510622, 0.08182533, 0.05979544, 0.07946499],
       [0.31313926, 0.03697876, 0.02281668, 0.        ]])

Converting the three normalised arrays into dataframes 

In [ ]:
df_12_16 = pd.DataFrame(array12_16_norm)

In [ ]:
df_4_8 = pd.DataFrame(array4_8_norm)

In [ ]:
df_8_12 = pd.DataFrame(array8_12_norm)

Following three codes are used for saving the normalised data frame in the csv format.

In [ ]:
df_12_16.to_csv('df_12_16.csv')

In [ ]:
df_4_8.to_csv('df_4_8.csv')

In [ ]:
df_8_12.to_csv('df_8_12.csv')

In [ ]:
ones = np.where(array8_12_norm > 0, array8_12_norm, np.inf).min(axis=0, initial=1.0) #finds a list of nearest points that will be served by the hub.

In [ ]:
array8_12.min()

1.0

In [ ]:
ones[:10]

array([0.01199128, 0.01635174, 0.01744186, 0.01417151, 0.04651163,
       0.03924419, 0.03888081, 0.01526163, 0.02579942, 0.04287791])

In [ ]:
pot = pd.read_csv('Pot.csv') #The potential data set was edited as Pot.csv to work only on the relevant columns.

In [ ]:
pot.sort_values(inplace=True, by='density')

In [ ]:
pot = pot['density'] #density data was extracted to be used in the genetic algorithm.

The following code was used to find the value which can be used to normalize the fitness function. We were trying to work with the case when every demand point is served by the nearest potential location.

In [ ]:
pot.head()

2     0.004889
14    0.004889
82    0.007333
47    0.007333
53    0.009333
Name: density, dtype: float64

In [ ]:
pot = pot[:62]

In [ ]:
pot.shape

(62,)

In [ ]:
pot = pot.to_numpy()

In [ ]:
sum(ones/10)

1.7277252906976754

In [ ]:
value = 1/(sum(pot/10) + sum(ones/10)) #this value was used to normalise the fitness function.

In [ ]:
value

0.4936286901687098